services:
  - type: web
    name: match-3-game
    runtime: node
    buildCommand: yarn install --production=true
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: match-3-game-db
          property: connectionString

databases:
  - name: match-3-game-db
    databaseName: eat_turntable
    user: eat_game
    plan: free
