services:
  - type: web
    name: match-3-game
    runtime: node
    rootDir: match-3-game
    buildCommand: yarn install --production=true
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
